---
- name: Install apache on web servers
  tags: apache
  package:
    name: 
      - "{{ webserver_package }}"
      - "{{ php_package }}"
  
- name: Copy html file
  tags: website
  copy: 
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  notify: restart_apache
